default: &default
adapter: postgresql
encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopper_development
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: postgres
  password: postgres
  test:
  <<: *default
  database: shopper_test

production:
  <<: *default
  database: shopper_production
  username: shopper
  password: <%= ENV['SHOPPER_DATABASE_PASSWORD'] %>